name = "futureclarity-tech"
compatibility_date = "2024-01-01"

[env.production]
name = "futureclarity-tech"
routes = [
  { pattern = "futureclarity.pages.dev/*", zone_name = "pages.dev" }
]

# Static site configuration
[site]
bucket = "./dist"
