// Generated by `deno task build:web` from backend/supabase/functions/_shared/.
// Do not edit by hand: change the TypeScript sources and rebuild.
(() => {
  // backend/supabase/functions/_shared/advice.ts
  var SPECIES_PROFILES = [
    {
      key: "citrus",
      label: "Citrus (orange, lemon, lime\u2026)",
      noun: "citrus",
      size: "large",
      low: 35,
      high: 55,
      why: "Citrus prefers consistent moisture but tolerates moderate drying; mature trees can sit in the mid-30s for a while (UC IPM suggests 4\u20136 inches of water a month in summer). Chronic saturation invites root and crown rot.",
      sourceLabel: "UC IPM: Citrus watering",
      sourceUrl: "https://ipm.ucanr.edu/PMG/GARDEN/FRUIT/CULTURAL/citruswatering.html"
    },
    {
      key: "avocado",
      label: "Avocado",
      noun: "avocado",
      size: "large",
      low: 40,
      high: 60,
      why: "Avocados have shallow feeder roots and dislike both drought and wet feet (about 2 inches of water a week in summer). Sustained high moisture leads to Phytophthora root rot.",
      sourceLabel: "California Avocado Commission: Irrigating avocado trees",
      sourceUrl: "https://www.californiaavocadogrowers.com/cultural-management-library/irrigating-avocado-trees"
    },
    {
      key: "camellia",
      label: "Camellia",
      noun: "camellia",
      size: "medium",
      low: 35,
      high: 50,
      why: "Camellias are more often killed by over-watering than under-watering. Keep moisture moderate and even and protect them from hot afternoon sun; bud drop signals summer water stress.",
      sourceLabel: "UC Master Gardeners: Camellia",
      sourceUrl: "https://ucanr.edu/blog/uc-master-gardeners-diggin-it-slo/article/camellia"
    },
    {
      key: "hydrangea",
      label: "Hydrangea",
      noun: "hydrangea",
      size: "medium",
      low: 40,
      high: 60,
      why: "Hydrangea macrophylla needs consistently moist, well-drained soil and wilts visibly when dry. It tolerates full sun only with steady moisture.",
      sourceLabel: "Missouri Botanical Garden: Hydrangea macrophylla",
      sourceUrl: "https://www.missouribotanicalgarden.org/PlantFinder/PlantFinderDetails.aspx?taxonid=286874"
    },
    {
      key: "rosemary",
      label: "Rosemary",
      noun: "rosemary",
      size: "small",
      low: 18,
      high: 35,
      why: "A drought-adapted Mediterranean shrub that needs no summer water once established. Roots need air between waterings; moisture held above about 35% invites crown rot.",
      sourceLabel: "UC Master Gardeners: Rosemary",
      sourceUrl: "https://sonomamg.ucanr.edu/Plant_of_the_Month/Rosemary"
    },
    {
      key: "lavender",
      label: "Lavender",
      noun: "lavender",
      size: "small",
      low: 20,
      high: 38,
      why: "Drought-tolerant, and excellent drainage is essential: a few days of saturated soil can cause root rot. A dry/wet cycle keeps it healthy, not constant moisture.",
      sourceLabel: "UC Master Gardeners: Lavandula",
      sourceUrl: "https://ucanr.edu/site/uc-master-gardener-program-sonoma-county/lavandula-lavender"
    },
    {
      key: "westringia",
      label: "Westringia (coast rosemary)",
      noun: "westringia",
      size: "small",
      low: 20,
      high: 38,
      why: "Coast rosemary is drought-tolerant and wants the soil to dry between deep waterings. Moisture held above 40% is a long-term mortality risk.",
      sourceLabel: "UC Master Gardeners: Westringia",
      sourceUrl: "https://ucanr.edu/site/uc-marin-master-gardeners/article/westringia-every-garden"
    },
    {
      key: "bay_laurel",
      label: "Bay laurel",
      noun: "bay laurel",
      size: "medium",
      low: 22,
      high: 40,
      why: "Established bay laurel (two years or more) adapts to low water. Sustained high moisture in clay soil is the bigger risk, so water deeply and infrequently.",
      sourceLabel: "UC Master Gardeners: Laurus nobilis",
      sourceUrl: "https://sonomamg.ucanr.edu/Plant_of_the_Month/Laurus_nobilis_Saratoga/"
    },
    {
      key: "star_jasmine",
      label: "Star jasmine",
      noun: "star jasmine",
      size: "medium",
      low: 30,
      high: 50,
      why: "Established star jasmine needs modest, periodic irrigation, with a little more in extreme heat. Well-drained soil only; it does not tolerate constantly wet roots.",
      sourceLabel: "UC IPM: Star jasmine",
      sourceUrl: "https://ipm.ucanr.edu/PMG/GARDEN/PLANTS/starjasmine.html"
    },
    {
      key: "boxwood",
      label: "Boxwood",
      noun: "boxwood",
      size: "medium",
      low: 28,
      high: 50,
      why: "Boxwood prefers slow, deep watering over frequent shallow watering. Use drip irrigation: overhead water spreads boxwood blight.",
      sourceLabel: "UC Master Gardeners: Drought watering",
      sourceUrl: "https://ucanr.edu/site/uc-master-gardener-program-alameda-county/thirsty-plants-and-watering-times-drought"
    },
    {
      key: "convolvulus",
      label: "Convolvulus (silverbush)",
      noun: "convolvulus",
      size: "small",
      low: 20,
      high: 40,
      why: "Silverbush is a Mediterranean groundcover, drought-tolerant once established. Moisture held above 40% causes root rot, so it needs excellent drainage.",
      sourceLabel: "UC IPM: Bush morning glory",
      sourceUrl: "https://ipm.ucanr.edu/PMG/GARDEN/PLANTS/bushmorngl.html"
    },
    {
      key: "unknown",
      label: "Other / not sure",
      noun: null,
      size: "medium",
      low: 25,
      high: 45,
      why: "No plant type is set, so a generic moderate-water band is used. Pick a type to get a species-specific range.",
      sourceLabel: null,
      sourceUrl: null
    }
  ];
  var PROFILE_BY_KEY = new Map(SPECIES_PROFILES.map((p) => [
    p.key,
    p
  ]));
  function getSpecies(key) {
    return PROFILE_BY_KEY.get(key ?? "") ?? PROFILE_BY_KEY.get("unknown");
  }
  var THRESHOLDS = {
    /** A plant this far below its floor is "very dry" and gets a deep soak. */
    veryDryGap: 10,
    /** From this far below the floor a moderate (not light) watering is suggested. */
    moderateGap: 5,
    /** Rain forecast within 48 h that defers watering for a dry (not very dry) plant. */
    deferRainIn48h: 0.25,
    /** Rain forecast within 24 h that also defers watering for a very dry plant. */
    deferRainIn24h: 0.5,
    /**
     * If the forecast reports precipitation probability and its 48 h maximum is
     * below this (%), forecast rain is ignored and watering advice is unchanged.
     */
    minRainProbability: 50
  };
  var WATERING_GALLONS = {
    small: {
      light: [
        0.5,
        1
      ],
      moderate: [
        1.5,
        3
      ],
      deep: [
        3,
        5
      ]
    },
    medium: {
      light: [
        1,
        2
      ],
      moderate: [
        4,
        6
      ],
      deep: [
        6,
        10
      ]
    },
    large: {
      light: [
        2,
        4
      ],
      moderate: [
        6,
        10
      ],
      deep: [
        12,
        18
      ]
    }
  };
  var EMITTER_GPH = 2;
  var EMITTERS_PER_PLANT = {
    small: 1,
    medium: 2,
    large: 4
  };
  function dripRateGph(size) {
    return EMITTER_GPH * EMITTERS_PER_PLANT[size];
  }
  function dripMinutes(gallons, size) {
    const minutes = gallons / dripRateGph(size) * 60;
    return Math.max(5, Math.round(minutes / 5) * 5);
  }
  var LEVEL_LABEL = {
    light: "Light watering",
    moderate: "Moderate watering",
    deep: "Deep soak"
  };
  function wateringPlan(size, level, band) {
    const [gallonsLow, gallonsHigh] = WATERING_GALLONS[size][level];
    const minutesLow = dripMinutes(gallonsLow, size);
    const minutesHigh = dripMinutes(gallonsHigh, size);
    const rate = dripRateGph(size);
    const targetPct = Math.round((band.low + band.high) / 2);
    return {
      level,
      gallonsLow,
      gallonsHigh,
      minutesLow,
      minutesHigh,
      dripRateGph: rate,
      targetPct,
      text: `${LEVEL_LABEL[level]}: ${gallonsLow}\u2013${gallonsHigh} gal, about ${formatDuration(minutesLow, minutesHigh)} of drip at ${rate} gal/h. Aim for about ${targetPct}%.`
    };
  }
  var HEADLINES = {
    very_dry: "Very dry",
    dry: "Dry",
    dry_rain_coming: "Rain coming",
    good: "Good",
    too_wet: "Too wet",
    no_reading: "No reading"
  };
  function isPercent(value) {
    return typeof value === "number" && Number.isFinite(value) && value >= 0 && value <= 100;
  }
  function resolveBand(profile, idealLow, idealHigh) {
    const low = isPercent(idealLow) ? Math.round(idealLow) : profile.low;
    const high = isPercent(idealHigh) ? Math.round(idealHigh) : profile.high;
    if (low >= high) return {
      low: profile.low,
      high: profile.high,
      custom: false
    };
    return {
      low,
      high,
      custom: low !== profile.low || high !== profile.high
    };
  }
  function actionableRain(rain) {
    if (!rain) return null;
    const p = rain.maxProbability48h;
    if (typeof p === "number" && Number.isFinite(p) && p < THRESHOLDS.minRainProbability) {
      return null;
    }
    const in24 = finiteOrZero(rain.next24hIn);
    const in48 = Math.max(finiteOrZero(rain.next48hIn), in24);
    return {
      in24,
      in48
    };
  }
  function assessPlant(input) {
    const profile = getSpecies(input.species);
    const band = resolveBand(profile, input.idealLow, input.idealHigh);
    const subject = band.custom ? "this plant's custom" : profile.noun ? `the ${profile.noun}` : "the";
    const bandText = `${subject} ${band.low}\u2013${band.high}% band`;
    if (!isPercent(input.moisture)) {
      return {
        status: "no_reading",
        headline: HEADLINES.no_reading,
        needsWater: false,
        advice: "The sensor isn't reporting. Check its battery and its range to the gateway.",
        explanation: "There is no current reading from this sensor, so there is nothing to evaluate.",
        watering: null,
        band,
        profile,
        moisture: null
      };
    }
    const m = Math.round(input.moisture);
    const rain = actionableRain(input.rain);
    const base = {
      band,
      profile,
      moisture: m
    };
    if (m > band.high) {
      const over = m - band.high;
      const moreRain = rain && rain.in48 >= THRESHOLDS.deferRainIn48h ? ` More rain (${formatInches(rain.in48)}) is forecast, so check that the bed drains.` : "";
      return {
        ...base,
        status: "too_wet",
        headline: HEADLINES.too_wet,
        needsWater: false,
        advice: `Hold off: ${m}% is ${points(over)} above the ${band.high}% ceiling. Let the soil dry out before watering again.${moreRain}`,
        explanation: `At ${m}% the soil is ${points(over)} above the top of ${bandText}. Roots held above this band for long can rot even when the surface looks dry.`,
        watering: null
      };
    }
    const gap = band.low - m;
    if (gap <= 0) {
      return {
        ...base,
        status: "good",
        headline: HEADLINES.good,
        needsWater: false,
        advice: `In range: ${m}% is inside the ${band.low}\u2013${band.high}% band. No action needed.`,
        explanation: `At ${m}% the soil is inside ${bandText}.`,
        watering: null
      };
    }
    const below = `${m}% is ${points(gap)} below the ${band.low}% floor`;
    const dryExplanation = (word) => `At ${m}% the soil is ${points(gap)} below the bottom of ${bandText}, so it reads as ${word}.`;
    if (gap < THRESHOLDS.veryDryGap) {
      if (rain && rain.in48 >= THRESHOLDS.deferRainIn48h) {
        return {
          ...base,
          status: "dry_rain_coming",
          headline: HEADLINES.dry_rain_coming,
          needsWater: false,
          advice: `Skip watering: ${formatInches(rain.in48)} of rain is forecast in the next 48 h and ${below}. Water if the rain doesn't arrive.`,
          explanation: `${dryExplanation("dry")} Watering is deferred because at least ${formatInches(THRESHOLDS.deferRainIn48h)} of rain is forecast within 48 hours.`,
          watering: null
        };
      }
      const level = gap >= THRESHOLDS.moderateGap ? "moderate" : "light";
      return {
        ...base,
        status: "dry",
        headline: HEADLINES.dry,
        needsWater: true,
        advice: `${level === "light" ? "Water lightly today" : "Water today"}: ${below}.`,
        explanation: dryExplanation("dry"),
        watering: wateringPlan(profile.size, level, band)
      };
    }
    if (rain && rain.in24 >= THRESHOLDS.deferRainIn24h) {
      return {
        ...base,
        status: "dry_rain_coming",
        headline: HEADLINES.dry_rain_coming,
        needsWater: false,
        advice: `Hold off: ${formatInches(rain.in24)} of rain is forecast in the next 24 h, enough to rewet the soil, although ${below}. Check again after the rain.`,
        explanation: `${dryExplanation("very dry")} Watering is deferred because at least ${formatInches(THRESHOLDS.deferRainIn24h)} of rain is forecast within 24 hours.`,
        watering: null
      };
    }
    if (rain && rain.in48 >= THRESHOLDS.deferRainIn48h) {
      return {
        ...base,
        status: "very_dry",
        headline: HEADLINES.very_dry,
        needsWater: true,
        advice: `Water today, but go lighter: ${below}, and ${formatInches(rain.in48)} of rain is forecast in the next 48 h.`,
        explanation: `${dryExplanation("very dry")} Forecast rain covers part of the deficit, so the suggested amount is one step lighter than a deep soak.`,
        watering: wateringPlan(profile.size, "moderate", band)
      };
    }
    return {
      ...base,
      status: "very_dry",
      headline: HEADLINES.very_dry,
      needsWater: true,
      advice: `Deep-water today: ${below}.`,
      explanation: dryExplanation("very dry"),
      watering: wateringPlan(profile.size, "deep", band)
    };
  }
  function finiteOrZero(value) {
    return typeof value === "number" && Number.isFinite(value) && value > 0 ? value : 0;
  }
  function points(n) {
    return `${n} point${n === 1 ? "" : "s"}`;
  }
  function formatInches(value) {
    return `${Number(value.toFixed(2))} in`;
  }
  function formatDuration(minutesLow, minutesHigh) {
    return `${minutesLow}\u2013${minutesHigh} min`;
  }

  // backend/supabase/functions/_shared/report.ts
  function emptyWeather() {
    return {
      available: false,
      temp_now_f: null,
      humidity_now: null,
      high_today_f: null,
      low_today_f: null,
      min_humidity_today: null,
      rain_today_in: null,
      high_tomorrow_f: null,
      rain_tomorrow_in: null,
      rain_next_24h_in: null,
      rain_next_48h_in: null,
      rain_probability_48h: null
    };
  }
  function rainOutlook(weather) {
    if (!weather?.available) return null;
    return {
      next24hIn: weather.rain_next_24h_in,
      next48hIn: weather.rain_next_48h_in,
      maxProbability48h: weather.rain_probability_48h
    };
  }
  function speciesCatalog() {
    return SPECIES_PROFILES.map((p) => ({
      key: p.key,
      label: p.label,
      low: p.low,
      high: p.high,
      why: p.why,
      source_label: p.sourceLabel,
      source_url: p.sourceUrl
    }));
  }
  function describeSourceError(error) {
    switch (error.kind) {
      case "auth":
        return "Ecowitt rejected the saved API keys, so no readings could be fetched. The sensors are probably fine; update the keys in setup.";
      case "device":
        return "Ecowitt does not recognise this gateway on the saved account. Check that the gateway is still registered in the Ecowitt app.";
      case "http":
      case "network":
      case "timeout":
        return "Couldn't reach the Ecowitt API, so there is no current reading. It will retry on the next refresh.";
      case "api":
        return `The Ecowitt API returned an error (${error.message}), so there is no current reading.`;
    }
  }
  var MISSING_GATEWAY = {
    kind: "device",
    message: "Gateway not found",
    code: null
  };
  function buildReport(input) {
    const gatewaysById = new Map(input.gateways.map((g) => [
      g.id,
      g
    ]));
    const zonesById = new Map(input.zones.map((z) => [
      z.id,
      z
    ]));
    const rain = rainOutlook(input.weather);
    const readings = input.plants.map((plant) => {
      const gateway = gatewaysById.get(plant.gateway_id);
      const gatewayName = gateway?.name ?? "Unknown gateway";
      const zone = plant.zone_id === null ? void 0 : zonesById.get(plant.zone_id);
      const result = input.gatewayResults[plant.gateway_id] ?? {
        ok: false,
        error: MISSING_GATEWAY
      };
      const channel = result.ok ? result.channels[plant.channel] : void 0;
      const assessment = assessPlant({
        moisture: channel?.moisture ?? null,
        species: plant.species,
        idealLow: plant.ideal_low,
        idealHigh: plant.ideal_high,
        rain
      });
      return {
        plant_id: plant.id,
        gateway_id: plant.gateway_id,
        zone_id: zone ? zone.id : null,
        zone: gatewayName,
        gateway_name: gatewayName,
        channel: plant.channel,
        display_order: plant.display_order ?? plant.channel,
        physical_zone: zone?.name ?? gatewayName,
        physical_zone_verified: true,
        name: plant.name,
        verified: true,
        pair: null,
        pair_role: null,
        battery: channel?.battery ?? null,
        notify: plant.notify ?? false,
        last_seen: input.lastSeen?.[plant.id] ?? null,
        last_battery: null,
        ...assessmentFields(assessment, result.ok ? null : describeSourceError(result.error))
      };
    });
    const zoneSort = (r) => {
      const zone = r.zone_id === null ? void 0 : zonesById.get(r.zone_id);
      return zone ? zone.sort : Number.MAX_SAFE_INTEGER;
    };
    readings.sort((a, b) => zoneSort(a) - zoneSort(b) || a.display_order - b.display_order || a.gateway_name.localeCompare(b.gateway_name) || a.channel - b.channel);
    const gateways = input.gateways.map((g) => {
      const result = input.gatewayResults[g.id];
      const error = result ? result.ok ? null : result.error : MISSING_GATEWAY;
      return {
        id: g.id,
        name: g.name,
        ok: error === null,
        error
      };
    });
    return {
      generated_at: input.generatedAt.toISOString(),
      weather: input.weather ?? emptyWeather(),
      counts: countReadings(readings),
      pair_notes: {},
      readings,
      zones: [
        ...input.zones
      ].sort((a, b) => a.sort - b.sort || a.name.localeCompare(b.name)),
      gateways,
      source_errors: gateways.flatMap((g) => g.error ? [
        {
          ...g.error,
          gateway_id: g.id,
          gateway_name: g.name
        }
      ] : []),
      species_catalog: speciesCatalog(),
      ...input.user ? {
        user: input.user
      } : {}
    };
  }
  function assessmentFields(a, offlineCause) {
    const { profile, band, watering } = a;
    return {
      species: profile.noun,
      type: profile.key,
      ideal_low: band.low,
      ideal_high: band.high,
      custom_range: band.custom,
      moisture: a.moisture,
      status: a.status,
      // A gateway failure explains itself; the sensor itself may be fine.
      headline: offlineCause ? "No data" : a.headline,
      advice: offlineCause ?? a.advice,
      needs_water: a.needsWater,
      rating_explanation: offlineCause ? "No data from the gateway, so there is nothing to evaluate." : a.explanation,
      watering_recommendation: watering?.text ?? null,
      watering_target_pct: watering?.targetPct ?? null,
      watering: watering ? {
        level: watering.level,
        gallons_low: watering.gallonsLow,
        gallons_high: watering.gallonsHigh,
        minutes_low: watering.minutesLow,
        minutes_high: watering.minutesHigh,
        drip_rate_gph: watering.dripRateGph,
        target_pct: watering.targetPct
      } : null,
      species_note: profile.why,
      source_label: profile.sourceLabel,
      source_url: profile.sourceUrl,
      offline_cause: offlineCause
    };
  }
  function reassess(reading, idealLow, idealHigh, weather) {
    const assessment = assessPlant({
      moisture: reading.moisture,
      species: reading.type,
      idealLow,
      idealHigh,
      rain: rainOutlook(weather)
    });
    return {
      ...reading,
      ...assessmentFields(assessment, reading.offline_cause)
    };
  }
  function countReadings(readings) {
    const counts = {
      needs_water: 0,
      too_wet: 0,
      good: 0,
      missing: 0,
      waiting_for_rain: 0
    };
    for (const r of readings) {
      if (r.needs_water) counts.needs_water++;
      else if (r.status === "too_wet") counts.too_wet++;
      else if (r.status === "good") counts.good++;
      else if (r.status === "no_reading") counts.missing++;
      else if (r.status === "dry_rain_coming") counts.waiting_for_rain++;
    }
    return counts;
  }

  // scripts/web_engine_entry.ts
  var engine = {
    assessPlant,
    buildReport,
    countReadings,
    emptyWeather,
    getSpecies,
    rainOutlook,
    reassess,
    resolveBand,
    speciesCatalog,
    SPECIES_PROFILES,
    THRESHOLDS
  };
  globalThis.PlantWatchEngine = engine;
})();
