/**
 * Bundles the advice engine (backend/supabase/functions/_shared/advice.ts and
 * report.ts) into web/js/engine.js, a classic script the dashboard loads with
 * no build step of its own. The web client uses it to re-evaluate a plant the
 * moment its range is edited, and demo mode uses it to build reports from
 * fixture data. CI rebuilds it and fails if the committed file is stale.
 *
 *   deno task build:web
 */

const root = new URL("../", import.meta.url);
const output = "web/js/engine.js";

const { code, stderr } = await new Deno.Command(Deno.execPath(), {
  args: [
    "bundle",
    "--quiet",
    "--platform=browser",
    "--format=iife",
    `--output=${output}`,
    "scripts/web_engine_entry.ts",
  ],
  // Run from the repository root so the path comments esbuild emits are
  // relative and the output is identical on every machine.
  cwd: root,
  stderr: "piped",
}).output();
if (code !== 0) {
  console.error(new TextDecoder().decode(stderr));
  Deno.exit(code);
}

const file = new URL(output, root);
const banner = "// Generated by `deno task build:web` from backend/supabase/functions/_shared/.\n" +
  "// Do not edit by hand: change the TypeScript sources and rebuild.\n";
await Deno.writeTextFile(file, banner + await Deno.readTextFile(file));
console.log(`Wrote ${output}`);
